<?php

/**
 * @file
 * Contains as_courses.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Fetches list of courses by semester and course prefix
 */

function as_courses_get_courses_json($semester,$subjects) {
// set cache id (verify parameters are safe values to use as cache id)
$cid = "as_courses:" . $semester . ":" . $subjects;
$courses_json = NULL;
//check cache
if ($cache = \Drupal::cache('data')->get($cid)) {
    //fetch cache data
    $courses_json = $cache->data;
} else {
    // if no cache data check url
    $url = "https://classes.cornell.edu/api/2.0/search/classes.json?roster={$semester}&subject={$subjects}";

    // curl
    //curl request
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_URL,$url);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10); 
    curl_setopt($ch, CURLOPT_TIMEOUT, 10); //timeout in seconds

    $data = curl_exec($ch);
    //$httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if (!empty($data)) {
        //dump($data);
        $json = json_decode($data, true);
    }

    if (!empty($json['data']['classes'])) {
        $courses_json = $json['data']['classes'];
        // set cache
        \Drupal::cache('data')
            ->set($cid, $courses_json, time()+3600); //cache for 1 hour
        }
    }
//return courses data
return $courses_json;
}


/**
 * Fetches list of courses by semester and instructor netid
 */

function as_courses_get_courses_netid_json($semester,$netid) {
//set cache id (verify parameters are safe values to use as cache id)
$cid = "as_courses:" . $semester . ":" . $netid;
$courses_json = NULL;
//check cache
if ($cache = \Drupal::cache('data')->get($cid)) {
    //fetch cache data
    $courses_json = $cache->data;
} else {
    // if no cache data check url
    $url = "https://classes.cornell.edu/api/2.0/search/classes.json?roster={$semester}&instructor={$netid}";

    // curl
    //curl request
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_URL,$url);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10); 
    curl_setopt($ch, CURLOPT_TIMEOUT, 10); //timeout in seconds

    $data = curl_exec($ch);
    //$httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if (!empty($data)) {
        $json = json_decode($data, true);
        //dump($json['data']['classes']);
    }

    if (!empty($json['data']['classes'])) {
        $courses_json = $json['data']['classes'];
        // set cache
        \Drupal::cache('data')
            ->set($cid, $courses_json, time()+3600); //cache for 1 hour
        }
    }

//return courses data
return $courses_json;
}


/**
 * Implements hook_help().
 */
function as_courses_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_courses module.
    case 'help.page.as_courses':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Turns json from classes.cornell.edu into twiggable data.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_courses_theme($existing, $type, $theme, $path) {
  return [
    'courses' => [
      'variables' => ['semester' => NULL, 'semestername' => NULL, 'course_prefixes' => NULL],
    ],
  ];
}
